### ISSUE TITLE
Manage User option is visible to inappropriate users,

### ISSUE THREAD

**Issue by munezerobagira** [atlp-rwanda/Team-Sostene-E-commerce-fe#47]
Manage user is visible when
- user have not logged in
- user have logged in and is not an admin
<img width="1357" alt="image" src="https://github.com/atlp-rwanda/Team-Sostene-E-commerce-fe/assets/42154315/fda58684-05e9-4bed-babc-5b3a8afcb8bb">

**Comment by Edcreation** [comment]
I think that will be Solved on PR #39 . Role Based access control.
