### ISSUE TITLE
Redirection using window.location.href 

### ISSUE THREAD

**Issue by munezerobagira** [atlp-rwanda/Team-Sostene-E-commerce-fe#54]
The redirection should be made using react router, using  window.location.href reduces the perfomance of the web.

This is applicable to
- Signup when user successfully signup
- Login when user successfully login
https://reactrouter.com/en/main/fetch/redirect
https://reactrouter.com/en/main/hooks/use-navigate

**Comment by Kress2000** [comment]
This needs to use `useNavigate `to redirect the user, and redux to keep the pathname, and redirect the user where he was, or was heading to. if pathname is empty, we redirect the user to the homepage
